### ISSUE TITLE
Use entry payload hash for operations instead of entry hash

### ISSUE THREAD

**Issue by adzialocha** [p2panda/handbook#156]
This simplifies the relationship of p2panda Operations and Bamboo Entries:

* Operations are identified by their hashes over the CBOR data (instead of by the entry hash they refer to)
* Bamboo entries become "verifiers" and "authenticators" for operations
* An Operation becomes "verified" if its hash is equal the payload hash of an verified entry it belongs to

Related notes: https://laub.liebechaos.org/leTbMWT1Qj6btn7-o6xrWA#

**Comment by cafca** [comment]
This seems related to the discussion of the `OperationWithMeta` naming & Magma/Lava.

The base of this is: How independent of Bamboo is p2panda? We have separated `Entry` and `Operation` because Bamboo was structured for that. Without Bamboo we probably would have made the separation at a different line, which is why we now have `OperationWithMeta` (which is `Operation` plus just a little bit of `Entry`). 

Identifying an operation by the entry hash means that authorship is part of the identity of an operation. If I create an operation `Berlin is where I live` that has a different truth-value than if Sam made that same operation so these two things should have _some_ different ID.

I think both the hash of an operation's CBOR and the hash of an entry are meaningful identifiers for an operation - just for different contexts.

This is a structure I had in mind earlier, not sure if it's helpful to change so many things now but hopefully I can contribute to this conversation regardless with it :D 

**A raw data type that is non-authenticated and has a signable encoding**

- just the raw `action`, `schema`, `fields` and `previous_operations` to place it in a graph
- independent of authorship
- identified by the hash of its CBOR representation
- Magma energy

**An authenticated data type that translates 1:1 into a transport-specific encoding (with Bamboo as the default transport)**

- wraps a `RawOperation`
- has an author 
- has a metadata field that contains transport-specific information
  - Bamboo is the default transport
  - metadata field contains all the Bamboo stuff (backlink, skiplink, seqnum, logid)
- can _always_ be converted 1:1 into the transport-specific datastructure (bamboo)
- identified by a hash over the encoding defined by its transport (entry hash)
- contains a signature over the transport-defined encoding to verify the authorship
- Lava energy

**Comment by adzialocha** [comment]
Ergo: We have to use entry hashes :crab:
