### ISSUE TITLE
When registering a schema in a node, do you support that particular version or all versions of that schema?

### ISSUE THREAD

**Issue by adzialocha** [p2panda/handbook#159]

**Comment by cafca** [comment]
In general I think that's a question for when we tackle schema migrations. 

One interesting though I had right now: you probably want to register schemas because you want your node to support a specific application. Applications will generally require a set of schemas to work properly so maybe we will want to have a mechanic that let's my node automatically register all schemas required for a specific or the latest version of an application. Different registered applications might also require different versions of the same schemas so it could be desirable to register different versions of the same schema at the same time.
