### ISSUE TITLE
Rules for protocol versions and version bumps

### ISSUE THREAD

**Issue by cafca** [p2panda/handbook#196]
When are we increasing the version of operations for example?

**Comment by adzialocha** [comment]
One could understand the p2panda protocol as a specification of:

1) How data looks like (the only "real" data we have is entries and operations)
2) How data can be written and queried (GraphQL Node API and Client API, qp2p, TLS 1.3)
3) How data is processed with what rules (Validation, Materialization, etc. with the help of our "abstract" concepts of schemas, document views, documents etc.)

.. these could be seen as the three "categories" of our _core_ specification (maybe I forgot one, we could add some more when necessary). This core specification is defined as:

> You _need_ to implement and follow all of these rules to be able to participate in the p2panda network.

The distinction between "real" data and "abstract" data is helpful in a way where we can _always_ delete materialized schemas, document views and what not and rebuild it from "real" data but not the other way around. So operations and entries are crucial, while all other data is "just" the result of processing them.

There is probably more categories for the _protocol extensions_, like blobs or different replication mechanisms? etc. I would say that extensions are defined by:

> a) Protocol specifications which do not require the "core specification" to change b) A node / client can easily ignore the extension, it will not break if it doesn't support it (basically the opposite of the core specification which is mandatory)

With all of this in mind I'd suggest:

* We have a version for each of these categories, meaning there is a protocol version for the data, one protocol version for the processing of data ("the flow"), one protocol version for the API
* We can for example bump "the processing flow" version and say, "from now on when we see a DELETE operation it needs to do x instead of y now" and nodes _can_ implement that flow. They can say "my node implementation follows the p2panda flow spec v3 so my documents are now doing x instead of y when I see a DELETE operation", people can see that from the outside and _expect_ a certain behaviour from a node by looking at the version
* We can for example bump the API version and say, "from now on `publish` is called `transmogrify` and it takes different parameters than before" aka, a "breaking API change", people can look at that from the outside and _expect_ that the API looks like that by looking at the version
* We can for example bump the operation version and say "from now on `previous_operations` is called `tipsy_tips`" or "entries take a new digital signature algorithm, we deprecate ed25519 because its inherently insecure and broken", aka a "breaking operation change", people can look at that from the outside and _expect_ that operations are shaped in that way

**Comment by adzialocha** [comment]
To bump the Bamboo entry version we can use the `tag` field by the way (its also suggested in the Bamboo specification)

**Comment by adzialocha** [comment]
Regarding the topic of "who cares, I implement things the way I want them to be and just fork p2panda" .. thats very common and likely to happen, but I guess then you a) either don't participate in the "other" network (similar to Ethereum Main Net and Ethereum Classic) or you b) break each others stuff horribly or not (its a social thing, like its happening with Activity Pub) c) you introduce your own versioning scheme next to ours (my p2panda fork is `penguin-v12`)

**Comment by cafca** [comment]
Instead of real data/abstract data I would maybe say source data/derived data

**Comment by cafca** [comment]
It's an interesting idea, I want to think about it more! Could you imagine an alternative where for the processes specifically we have a list of capabilities instead, e.g. `[materialiser_base_v3, document_deletion_v1, materialiser_client_api_v5]` and implementations can fulfill any combination of these? If you interface with a node/client you check that your required capabilities are fulfilled and ignore all others you don't know.

**Comment by adzialocha** [comment]
> It's an interesting idea, I want to think about it more! Could you imagine an alternative where for the processes specifically we have a list of capabilities instead, e.g. `[materialiser_base_v3, document_deletion_v1, materialiser_client_api_v5]` and implementations can fulfill any combination of these? If you interface with a node/client you check that your required capabilities are fulfilled and ignore all others you don't know.

Yeah I also wonder if it could be separated into even smaller bits. There are maybe some dangers though:

1. We could confuse configuration with specification. Instead we should write the specification to allow turning parts of the system on/off or adjuating them through our (future) config schema
2. We make the specification process more complicated. For example: if we change the "deletion spec" but that will cause an incompatibility with the other "partial replication" spec how do we reflect that? Do we build a dependency tree between "sub spec versions"? That just might be harder to parse then saying the general spec is bumped, even if it only affected 1 or 2 sub systems.
3. I still think that finding good sub sections of the spec is great for the readability and lowering implementation threshold, but maybe they don't need separate versions

**Comment by sandreae** [comment]
I really like thinking about the different layers as you describe them, I started understanding things a little like this recently and it felt quite natural.

It gets hard for me to logic out when thinking about where there are dependencies between these different layers. For example, operations contain..... `DocumentViewId` in `previous_operations` which depend on a a certain ordering algorithm being applied during materialization. So there are dependencies between these layers (not just API interfaces) even if we try to detach them conceptually. 

Does this idea include changing logic which is relied on in this way? So some older operation versions would be incompatible with a materialization bump which includes a breaking change (LWW is decided in a different way for example)? And we could communicate this somehow usefully?

**Comment by adzialocha** [comment]
> Does this idea include changing logic which is relied on in this way? So some older operation versions would be incompatible with a materialization bump which includes a breaking change (LWW is decided in a different way for example)? And we could communicate this somehow usefully?

Yeah every major version bump (semantic versioning) would indicate an incompatibility to previous specifications :+1:

**Comment by adzialocha** [comment]
1. We don't make a version 1 release for now
2. This implies breaking changes without version bumps (alpha) / operation version will not increment
3. This ticket is also about having version for different parts of the spec, but we can talk about that later
