### ISSUE TITLE
Replication by schema

### ISSUE THREAD

**Issue by adzialocha** [p2panda/handbook#203]

**Comment by sandreae** [comment]
Thinking about this a little more, and looking at what we currently have, I'm wondering what the simplest specification we could make is. Say we assume for now we would pass the `schema_id` as CLI arguments to an `aquadoggo` node (as we do now with public keys and log ids) to show which schema we want to replicate, then I can only see that we are missing knowledge about which public keys have contributed to a document (on the remote node) in order to implement replication by schema using the existing replication graphQL endpoints. Doing this would end up like:

`A` to `B`: I am interested in `schema_x`
`B` to `A`: I support that and these authors have published to it on these log ids: `[(pub_key_a, [log_id_1, log_id_27]), (pub_key_b, [log_id_6])]`
..... _from here `A` can continue using the existing replication methods_ 

For sure there are other ways to handle that negotiation, this seems like one relatively simple method only introducing one extra step. Interested to hear other approaches :+1:

**Comment by adzialocha** [comment]
Yes! The solution might be quiet simple and we don't need to add much. I think we could do this with a `schemas` GraphQL query, giving you which log ids & authors published which schema.
