### ISSUE TITLE
Specify one node per author

### ISSUE THREAD

**Issue by sandreae** [p2panda/handbook#249]
In order to prevent keys from publishing on more than one node we should add a check during publishing.

Nodes should keep a list (or hashtable) of all keys they are hosting and all keys they have seen on other nodes during replication and use this to a) reject publish for keys that are known to be hosted elsewhere b) reject replication for new entries from keys that the node hosts itself (and maybe warn the remote node about this conflict).

originally posted by @cafca https://github.com/p2panda/handbook/issues/195

**Comment by sandreae** [comment]
So, this is one of the more beefy validation requirements we haven't implemented yet.

It would require something along the lines of:
- keeping track of all public keys we know about as well as whether there entries arrived via the replication api or the `publish` api
- if any public key we know about via replication should be blocked from then publishing via `publish`
- entries by any public key we know about via `publish` should be blocked from arriving via replication

I believe this method would fulfil the spec requirements but I haven't fully groked if there are difficult edge cases/consequences.

One case I can already think of is if you wiped your own local node and repopulated from the network you would no longer be able to use any existing public keys associated with clients that have previously published data that the node re-retrieves.

**Comment by cafca** [comment]
I can see three ways of going about it: ignoring it, making it explicit or making it implicit.

Making it implicit would involve trying to infer which node a key is hosted on by looking at all its logs and where we received them from. This seems brittle.

Making it explicit would mean that keys register with a node before publishing. This would mean that nodes get their own public key/identity. We create a handshake by both node and client publishing documents that request/acknowledge that a specific key is hosted by a specific node. Now, the publish endpoint can be used by referring to the document id of the handshake as authorisation.

Ignoring it would be what we are currently doing where conflicts may just happen, when a key is used on more than one node.

---

Here is an example handshake protocol:

1. Node uses key `node`, client uses key `client`.
2. Client requests the public key `node` from a well-known GraphQL endpoint on that node.
3. `client` calls a GraphQL mutation endpoint `create_authorisation(public_key: string!)` with its own public key as argument.
4. `node` checks whether it knows about any other `node_authorisation` documents that match the public key and denies the request if that's the case. Otherwise it publishes a document that contains the public key of the client:
  ```yaml
  schema: node_authorisation_v1
  fields:
    public_key: string
  ```
5. `client` publishes a document that acknowledges the authorisation.
  ```yaml
  schema: node_authorisation_confirm_v1
  fields:
    confirm: relation(node_authorisation_v1)
  ```
6. Now, `client` is authorised to use `node` for publishing, which is also verifiable by any other node that replicates `node_authorisation_v1` documents.

The `publish` GraphQL endpoint is extended with a third parameter, `authorisation`, which must contain the document id of a `node_authorisation_v1` document. On publishing, the node checks that it has this document, that the document was published by itself, that the encoded entry that is sent to the `publish` mutation matches the public key contained in the document. If client wants to publish any schema that is not `node_authorisation_confirm_v1`, the node also checks that it has a `node_authorisation_confirm_v1` document that confirms the node authorisation from the client's side.

If at any point a situation occurs where a client has created a node authorisation with two different nodes, both of which went along with it because they didn't know about it, but it comes to light later on, only the authorisation that has the client's `node_authorisation_confirm_v1` with the lower log id is valid and all documents published through the other node must be considered invalid and not materialised.
