### ISSUE TITLE
Entry encoding validation

### ISSUE THREAD

**Issue by adzialocha** [p2panda/handbook#26]
#### Bamboo Entry Encoding

- Bytes encoded following the Bamboo specification: https://github.com/AljoschaMeyer/bamboo#encoding
	- We use BLAKE3 hashes wrapped in `yasmf` multi-hash format for `backlink`, `lipmaalink` (skiplink) and `payload_hash`
		- Specification here:
			- `blake3` https://blake3.io
			- `yamf` https://github.com/AljoschaMeyer/yamf-hash
			- `yasmf` https://github.com/bamboo-rs/yasmf-hash
	- We use `Ed25519` as a public-key signature system
		- Specification here:
			- https://ed25519.cr.yp.to/
	- Currently we encode, but do not make use of the `tag` marker. We reserve it for future protocol updates
		- It _needs_ to be set to `0`?

#### Log Integrity

TODO

**Comment by cafca** [comment]
Some questions:

- What happens when blake3 is discovered to be broken and another hash is added to yasmf?
  - Practically, implementations will probably add support for a replacement asap 
  - Therefore, I think we shouldn't write into the spec that Blake3 is _the_ hasher we use. We should just say "you MUST support _validating_ all hashes in yasmf andyou SHOULD use the one that was added last when _creating_ hashes"
- The yasmf repo doesn't list supported hashes like yamf, or explains how yasmf works. Should we publish a yasmf spec?

**Comment by adzialocha** [comment]
>   - Therefore, I think we shouldn't write into the spec that Blake3 is _the_ hasher we use. We should just say "you MUST support _validating_ all hashes in yasmf andyou SHOULD use the one that was added last when _creating_ hashes"

This sounds good! Isn't the last point even part of the yamf spec? It says that one should always use the latest added hashing algorithm, new ones will only be added if the previous broke.

> - The yasmf repo doesn't list supported hashes like yamf, or explains how yasmf works. Should we publish a yasmf spec?

Yes please! I thought about it yesterday as well when writing the learn chapter, hard to talk about yasmf when nothing is written down about it 👍 i thought we could fork Aljoschas repo and adjust it?

**Comment by sandreae** [comment]
Closed and raised issue regarding yasmf specification: https://github.com/p2panda/handbook/issues/250
