### ISSUE TITLE
Maximum payload size for entries / logs / operations

### ISSUE THREAD

**Issue by adzialocha** [p2panda/handbook#31]
Think about a maximum payload size for entries / logs (blobs), is it configurable or defined on protocol level? Or are these actually two separate things?

This could be configured on a per-schema level so that schema designers can design them explicitly for a specific usage scenario including specific target devices (and schemas can be excluded from replication).

**Comment by cafca** [comment]
IMHO:

* the specification should not define maximum payload size because that's too inflexible for the future
* we could make a recommendation, e.g. 512 kilobyte (large enough to base64 encode images in text fields)
* nodes should be able to advertise what they are willing to publish / replicate (part of an node's "about" gql object?)
* it could be interesting to make this part of the schema definition in the future, then node operators can anticipate payload sizes they will have to handle by the schemas they have allowed
